name: PJO Guitar Designs
favicon: null
layout_spectrum: 1
typography_spectrum: 0.35921567934565246
title: PJO Guitar Designs
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#180d0b'
    - '#fffffd'
    - '#433937'
    - '#b74e4d'
    - '#c58f55'
  brandStrength: 0.5130950030870736
  lightness: 0.25
  saturation: 0.6875
  rhythmicContrast: 0.5053237094543874
purpose: []
