name: PJO Guitar Designs
favicon: null
layout_spectrum: 0.71746
typography_spectrum: 0.35921567934565246
title: PJO Guitar Designs
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: UA-37085210-10
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#180d0b'
    - '#fffffd'
    - '#433937'
    - '#b74e4d'
    - '#c58f55'
  brandStrength: 0.5
  lightness: 0.4375
  saturation: 0.1875
  rhythmicContrast: 0.25
purpose: []
